entregalab/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

movies/urls.py
from django.urls import path

from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.MovieListView.as_view(), name='index'),
    path('create/', views.create_movie, name='create'),
    path('<int:movie_id>/', views.detail_movie, name='detail'),
    path('<int:movie_id>/review/', views.create_review, name='review'),
    path('lists/', views.ListListView.as_view(), name='lists'),
    path('lists/create', views.ListCreateView.as_view(), name='create-list'),
    path('update/<int:movie_id>/', views.update_movie, name='update'),
    path('delete/<int:movie_id>/', views.delete_movie, name='delete'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

movies/models.py
from django.db import models
from django.conf import settings


class Movie(models.Model):
    name = models.CharField(max_length=255)
    release_year = models.CharField(max_length=255)
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name} '


class Review(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    likes = models.IntegerField(default=0)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class List(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    movies = models.ManyToManyField(Movie)

    def __str__(self):
        return f'{self.name} '

staticpages/models.py
from django.db import models

# Create your models here.

movies/forms.py
from django.forms import ModelForm
from .models import Movie, Review
from django import forms

class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = [
            'name',
            'release_year',
            'poster_url',
        ]
        labels = {
            'name': 'Título',
            'release_year': 'Ingredientes',
            'poster_url': 'URL da Receita',
        }


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .temp_data import movie_data
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import Movie, Review
from django.views import generic
from .models import Movie, Review, List
from .forms import MovieForm, ReviewForm

        


def list_movies(request):
    context = {"movie_list": movie_data}
    return render(request, 'movies/index.html', context)

def create_movie(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie_name = form.cleaned_data['name']
            movie_release_year = form.cleaned_data['release_year']
            movie_poster_url = form.cleaned_data['poster_url']
            movie = Movie(name=movie_name,
                          release_year=movie_release_year,
                          poster_url=movie_poster_url)
            movie.save()
            return HttpResponseRedirect(
                reverse('movies:detail', args=(movie.id, )))
    else:
        form = MovieForm()
    context = {'form': form}
    return render(request, 'movies/create.html', context)
        




class MovieListView(generic.ListView):
    model = Movie
    template_name = 'movies/index.html'


def detail_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    context = {'movie': movie}
    return render(request, 'movies/detail.html', context)

def update_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)

    if request.method == "POST":
        form = MovieForm(request.POST)
        if form.is_valid():
            movie.name = form.cleaned_data['name']
            movie.release_year = form.cleaned_data['release_year']
            movie.poster_url = form.cleaned_data['poster_url']
            movie.save()
            return HttpResponseRedirect(
                reverse('movies:detail', args=(movie.id, )))
    else:
        form = MovieForm(
            initial={
                'name': movie.name,
                'release_year': movie.release_year,
                'poster_url': movie.poster_url
            })

    context = {'movie': movie, 'form': form}
    return render(request, 'movies/update.html', context)

def delete_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)

    if request.method == "POST":
        movie.delete()
        return HttpResponseRedirect(reverse('movies:index'))

    context = {'movie': movie}
    return render(request, 'movies/delete.html', context)

def create_review(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review_author = form.cleaned_data['author']
            review_text = form.cleaned_data['text']
            review = Review(author=review_author,
                            text=review_text,
                            movie=movie)
            review.save()
            return HttpResponseRedirect(
                reverse('movies:detail', args=(movie_id, )))
    else:
        form = ReviewForm()
    context = {'form': form, 'movie': movie}
    return render(request, 'movies/review.html', context)

class ListListView(generic.ListView):
        model = List
        template_name = 'movies/lists.html'


class ListCreateView(generic.CreateView):
    model = List
    template_name = 'movies/create_list.html'
    fields = ['name', 'author', 'movies']
    success_url = reverse_lazy('movies:lists')

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir nova receita</h2>
<form method="POST" action="{% url 'movies:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

movies/templates/movies/create_list.html
{% extends 'base.html' %}

{% block title %}
Criar receita
{% endblock title %}

{% block content %}
<h2>Criar Categoria</h2>

<form action="{% url 'movies:create-list' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

movies/templates/movies/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'movies:delete' movie.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar essa receita "{{ movie.name }} "?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block title %}
{{ movie.name }} ({{ movie.release_year }}
{% endblock title %}

{% block content %}
<h2>Detalhes da receita:  {{ movie.name }} </h2>

<section class="dados-de-filme">
    <img src="{{ movie.poster_url }}" alt="Poster do filme {{ movie.name}}">
    <ul>
        <li>Nome: {{ movie.name }}</li>
        <li>Ingredientes: {{ movie.release_year }} </li>
        {% if movie.list_set.all %}
        <li>Incluso nas categorias :<a href="{% url 'movies:lists' %}"> {{ movie.list_set.all|join:", " }} </a></li>
    {% endif %}
        <br>
        <br>
        <br>

        <li><a href="{% url 'movies:update' movie.id %}">Editar</a></li>
        <li><a href="{% url 'movies:delete' movie.id %}">Apagar</a></li>
    </ul>
</section>

<hr>

<section>
    <header>
        <h3>Comentários sobre a receita</h3>
    </header>
    <ul>
        {% if movie.review_set.all %}
            {% for review in movie.review_set.all %}
                <figure>
                    <blockquote>
                        "{{ review.text }}"
                    </blockquote>
                    <figcaption>—{{ review.author }}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário para esta receita.</p>
        {% endif %}
    </ul>
</section>

</ul>
    
<hr>

<a href="{% url 'movies:review' movie.pk %}"><button>Crie seu comentário</button></a>
</section>

{% endblock content %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos as Receitas</h2>
<section>
    
    <p>Deseja você também adicionar uma receita? <a href="{% url 'movies:create' %}">Adicionar Nova receita</a></p>
</section>
{% if movie_list %}
<section class="lista-de-cards">
    {% for movie in movie_list %}
    <article class="card">
        <a href="{% url 'movies:detail' forloop.counter %}"><img src="{{ movie.poster_url }}"
                alt="Poster do filme {{ movie.name}}"></a>
        <p>{{ movie.name }} </p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma receita.</p>
{% endif %}

{% endblock content %}

movies/templates/movies/lists.html
{% extends 'base.html' %}

{% block title %}
Categorias de receitas
{% endblock title %}

{% block content %}
<h2>Categorias de receitas</h2>

<section>
    {% for list in list_list %}
    <hr>
    <article>
        <header>
            <h3>{{list.name}}  </h3>
        </header>
        <div class="lista-de-cards">
            {% for movie in list.movies.all %}
            <div class="card">
                <a href="{% url 'movies:detail' movie.id %}"><img src="{{ movie.poster_url }}"
                        alt="Poster do filme {{ movie.name}}"></a>
                <p>{{ movie.name }}</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

    <a href="{% url 'movies:create-list' %}"><button>Crie sua Lista</button></a>
</section>

{% endblock content %}

movies/templates/movies/review.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar receita {{ movie.name }} </h2>

<form action="{% url 'movies:review' movie.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar comentário</button>
</form>

<p><a href="{% url 'movies:detail' movie.id %}">Voltar para a página da receita</a></p>
{% endblock content %}

movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar receita: {{ movie.name }}</h2>
<form method="POST" action="{% url 'movies:update' movie.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Receitas misteriosas</i></h1>
<p>O blog de receitas onde as pessoas podem adicionar os ingredientes e fotos de suas receitas... e nada mais!
    <br>
    Quer saber como a pessoa fez a comida da foto? Descubra por si!
</p>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Receitas misteriosas
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha -->
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo2.svg' %}"> </a>
        <a href="{% url 'index' %}">
            <p>Receitas misteriosas</p>
        </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'movies:index' %}">Receitas</a></li>
                <li><a href="{% url 'movies:lists' %}">Categorias</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>
        

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>